### ISSUE TITLE
como configuro o bot pra ele farm em duas contas?

### ISSUE THREAD

**Issue by megamandev** [renatofmmaia/bomb-bot#100]
dexo duas contas abertas na tela de login com os dois navegadores maximizados em tela cheia um sobre o outro, mas o bnot so faz as coisas em um.

**Comment by leandroxx** [comment]
quando tu liga o bot, ele diz quantass janelas de bomb cripto estão abertas que ele reconheceu, lembra que tem que ser janelas separadas, não pode ser na mesma aba

**Comment by megamandev** [comment]
pode ser navegadores diferentes
