### ISSUE TITLE
Funciona no firefox?

### ISSUE THREAD

**Issue by megamandev** [renatofmmaia/bomb-bot#104]
Funciona no firefox?

**Comment by leandroxx** [comment]
Sim, é independente do navegador

**Comment by megamandev** [comment]
@leandroxx

valeu leandroxx, to pensando em criar uma vps na oracle mas tao falando que expira com 30 dias vc sabe disso

**Comment by wsa7** [comment]
> @leandroxx
> 
> valeu leandroxx, to pensando em criar uma vps na oracle mas tao falando que expira com 30 dias vc sabe disso

Pode criar, uso 4 contas em cada IP. Esta a mais de 30 dias

**Comment by megamandev** [comment]
@wsa7

mas quais configuracoes vc usou, tipo de processador e memoria e sistema pra mim fazer igual
tem video tutorial q vc seguiu

**Comment by wsa7** [comment]
> @wsa7
> 
> mas quais configuracoes vc usou, tipo de processador e memoria e sistema pra mim fazer igual tem video tutorial q vc seguiu

https://www.youtube.com/watch?v=KTHbFm_IyAc&t=314s

**Comment by megamandev** [comment]
valeu ae todos vou ver o video

**Comment by megamandev** [comment]
@wsa7

vc criou 4 instance com 4 nucleos ou 1 nucleo cada instance
qual configuracao das suas instance brother. cpu memoria hd

**Comment by leandroxx** [comment]
4 instance com 1 nucleo cada e 6GB de RAM...
