### ISSUE TITLE
Bot fica parado.

### ISSUE THREAD

**Issue by juniorj1** [renatofmmaia/bomb-bot#11]
Quando chega na tela de colocar os heroes para trabalhar, simplesmente fica parado e depois atualiza o browser.

Usando Chrome, Windows 10 e Python 3.10.2

**Comment by KruegerVox** [comment]
Mesma coisa aqui, na escolha do herói ele para. Segue o log:

[2022-02-09 09:41:11] => Traceback (most recent call last):
  File "C:\bomb_NEW\main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\bomb_NEW\module\manager.py", line 38, in do_what_needs_to_be_done
    Hero.do_check_error(self)
  File "C:\bomb_NEW\module\bombScreen.py", line 295, in do_check_error
    BombScreen.go_to_heroes(manager)
  File "C:\bomb_NEW\module\bombScreen.py", line 105, in go_to_heroes
    BombScreen.wait_for_screen(BombScreenEnum.HEROES.value)
  File "C:\bomb_NEW\module\bombScreen.py", line 41, in wait_for_screen
    raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.')
Exception: Timeout waiting for screen HEROES.

**Comment by renatofmmaia** [comment]
O navegador de vocês esta com zoom? verifiquem por favor, se estiver, tem que manter em 100%, ou seja, sem zoom, pois altera a proporção na hora de comparar as imagens e o bot não localiza os targets.
![image](https://user-images.githubusercontent.com/5515430/153204182-f4568e8c-42d2-4270-8300-905b9cb11273.png)

**Comment by KruegerVox** [comment]
Aqui está em 100%

https://pasteboard.co/6Wlh0XhFwjHV.png

**Comment by LeandroBraccio** [comment]
Aqui também...fica parado na listagem de herois, pagina está 100%

**Comment by evertonurbanii** [comment]
Aqui tbm, fica parado depois da atualização.. até ontem a noite tava perfeito..

**Comment by hiagopinacio** [comment]
O bomb atualizou as cores, já subimos uma nova versão do bot. Se continuar o problema abre outra Issue pf.
