### ISSUE TITLE
.local bin nao esta adicionada ao PATH error

### ISSUE THREAD

**Issue by mattrocha01** [renatofmmaia/bomb-bot#112]
Se alguem puder me ajudar agradeco demais, eu ja conseguir rodar o bot... mas estou tendo essas mensagens quando instalando nessa nova VM que criei

![Captura de tela 2022-03-21 135217](https://user-images.githubusercontent.com/102055626/159316243-1ba7b4d9-9f1c-439f-9733-44e808ae1dda.png)

**Comment by LheonidasDev** [comment]
Já tentou rever a instalação dos módulos

**Comment by megamandev** [comment]
a solucao pra esse problema se encontra na pagina inicial onde vc baixa o bot la no final da pagina em possiveis solucoes

**Comment by mattrocha01** [comment]
Puatzzz.... valeu demais, passou despercebido. Obrigado @megamandev
