### ISSUE TITLE
Não envia foto para o telegram

### ISSUE THREAD

**Issue by juniorgtxx** [renatofmmaia/bomb-bot#120]
Hoje pela manhã percebi que os prints não foi enviado,ai eu refiz a configuração do bot ele não consegue enviar para o telegram

**Comment by megamandev** [comment]
ate onten estava funcionando, depois dessa nova atualizacao parou de enviar.. vou da uma estudada pra ver se consigo resolver

**Comment by juniorgtxx** [comment]
> ate onten estava funcionando, depois dessa nova atualizacao parou de enviar.. vou da uma estudada pra ver se consigo resolver

beleza,obrigado qualquer coisa se posta aqui.

**Comment by tgarrone** [comment]
Simples resolver.

Basta fazer o recorte novamente da imagem "chest_screen_for_geometry" que está localizada na pasta \assets\images\targets

Obs.: Pode utilizar a "Ferramenta de Captura" do próprio windows no caso, fazer o recorte igual ao original e salvar por  cima. Enjoy!

**Comment by Fetexer** [comment]
![image](https://user-images.githubusercontent.com/102748880/162042728-1fbaea5b-7c51-4010-87f2-b117751558a1.png)

é por causa da porra dessa barrinha

**Comment by juniorgtxx** [comment]
ajustei a imagem conforme foi feito e ainda o erro persiste vou por a imagem que editei aqui e o erro
[img]https://i.imgur.com/Fp59MRf.png[/img]
o erro
[img]https://i.imgur.com/AOQMuPK.png[/img]

**Comment by wsa7** [comment]
aqui tambem nao manda

**Comment by Fetexer** [comment]
aqui deu certo, eu tirei esse print acima, coloquei o nome de chest_screen_for_geometry, e substitui na pasta ( \assets\images\targets) do bot.

**Comment by juniorgtxx** [comment]
> aqui deu certo, eu tirei esse print acima, coloquei o nome de chest_screen_for_geometry, e substitui na pasta ( \assets\images\targets) do bot.

tem como disponibiliza a imagem sem o cursor da mão?

**Comment by Fetexer** [comment]
![chest_screen_for_geometry](https://user-images.githubusercontent.com/102748880/162235698-7c04a07a-2813-442d-bc0f-1f17efeee8b7.png)

**Comment by juniorgtxx** [comment]
> ![chest_screen_for_geometry](https://user-images.githubusercontent.com/102748880/162235698-7c04a07a-2813-442d-bc0f-1f17efeee8b7.png)

vlw cara deu certo,quem tiver com dificuldade gente só pega essa imagem ai
