### ISSUE TITLE
overflow (barras de rolagem) aparecendo

### ISSUE THREAD

**Issue by selique** [renatofmmaia/bomb-bot#141]
![image](https://user-images.githubusercontent.com/1678894/163765099-bfbd3a8a-9890-40af-912d-df2e6c6b6a31.png)

overflow (barras de rolagem) aparecendo, isso talvez esteja perturbando na hora dele reconhecer a imagem, alguém tem uma dica ou talvez devêssemos diminua a area de contato da comparação da imagem @renatofmmaia

**Comment by megamandev** [comment]
infelizmente vai ter que usar assim mesmo, ate os devs resolverem liberar novamente o site sem anuncios

**Comment by selique** [comment]
@megamandev @renatofmmaia consegui fazer funcionar com as imagens #132, 

se me add como colaborador ficarei feliz de contribuir minhas pull requests

**Comment by selique** [comment]
@megamandev @renatofmmaia consegui fazer funcionar com as imagens #132, 

se me add como colaborador ficarei feliz de contribuir minhas pull requests
