### ISSUE TITLE
Uma dica - Print Apenas da ABA aberta,

### ISSUE THREAD

**Issue by evertonurbanii** [renatofmmaia/bomb-bot#15]
Poderia configurar para o Print ser apenas da ABA aberta, dessa forma, daria para deixar as contas uma do lado da outra, pq o limitador atual é devido ao print ser da tela inteira. Alem disso, acredito que utilizaria ainda menos recursos da VM, sendo que teria uma menor area de verificação.

**Comment by renatofmmaia** [comment]
Fala@evertonurbanii, blza?
Para que o bot funcione em multi acc, vc tem que usar maximizado o navegador ou deixar as guias uma em cima da outra. Como ele usa reconhecimento de imagem, ele pode se confundir ao tentar identificar uma imagem em cada uma de suas ações, e para garantir que isso não aconteça, mantenha sempre uma tela acima da outra.

Se liga nesse exemplo:

![image](https://user-images.githubusercontent.com/5515430/153247236-e55bde2f-a298-4724-b3f0-f6f12ae2eca1.png)

**Comment by hiagopinacio** [comment]
Boa noite @evertonurbanii. Seria muito bom ter isso mesmo, mas infelizmente não encontramos uma maneira eficiente de pegar a posição da janela no linux. Tem uma biblioteca open source em desenvolvimento.
Quem sabe no futuro conseguimos colocar essa melhoria.
