### ISSUE TITLE
Help me - Update BC Problem

### ISSUE THREAD

**Issue by THEROTA** [renatofmmaia/bomb-bot#18]
I configured correctly but this message appears, could you help me to correct the error?

[2022-02-09 13:36:20] => 😬 Ohh no! A error has occurred in the last action.
Timeout waiting for screen HEROES.
 Check the log  file for more details.
![image](https://user-images.githubusercontent.com/99351394/153248122-c193df72-9788-418b-a694-555914ab195b.png)

**Comment by hiagopinacio** [comment]
The Bomb sprites have changed after the update. 
We update the Bot today. 
Your config is ok.  Just download the last version and run again.
