### ISSUE TITLE
Uma dica - Login Metamask

### ISSUE THREAD

**Issue by evertonurbanii** [renatofmmaia/bomb-bot#19]
Outra features interessante seria opção do bot logar automaticamente na metamask, facilitando assim quelquer situação de rebot da VM, onde é possivel automatizar todo o processo.

**Comment by hiagopinacio** [comment]
Boa. Seria complicado ter essa configuração pra multi acc. Hoje o bot não tem controle de qual tela está cada acc.
Obrigado pela sugestão.

**Comment by evertonurbanii** [comment]
Sim, a senha da metamask tem q ser a mesma para todas as contas. Tem um bot q ja faz isso hoje e por isso a ideia, é muito top.
