### ISSUE TITLE
Erro de multiacc

### ISSUE THREAD

**Issue by Tormuka** [renatofmmaia/bomb-bot#20]
Tenho o seguinte problema no linux com o bot, ele não muda de conta, fica aparecendo somente isso "bin/sh: 1: xdotool: not found
/bin/sh: 1: xdotool: not found
/bin/sh: 1: xdotool: not found
/bin/sh: 1: xdotool: not found
/bin/sh: 1: xdotool: not found
/bin/sh: 1: xdotool: not found
/bin/sh: 1: xdotool: not found"
E fica somente na pagina que ta aberta. 
Não aparece a opção de calculate windown oclusion no meu google chrome, mesmo habilitando o 96.

**Comment by andresandri2** [comment]
Você precisa instalar o pacote xdotool no seu linux. Seguem abaixo os comandos para Ubuntu, Fedora ou CentOS

sudo apt-get install xdotool 
ou
sudo yum install xdotool
ou
sudo pacman -S xdotool
