### ISSUE TITLE
telegram

### ISSUE THREAD

**Issue by CrazyChappie** [renatofmmaia/bomb-bot#22]
como faço pra enviar os logger no tele atualmente eles aparece so quando ta sendo executado

**Comment by hiagopinacio** [comment]
a única opção atualmente é deixar a tela dividida entre o terminal e o navegador.
daí no config.yaml vc muda `print_full_screen` pra `true`

![image](https://user-images.githubusercontent.com/54750249/153306006-7cee96dc-1a82-453e-9342-f1371bd1a0f7.png)
