### ISSUE TITLE
Erro ao executar "python main.py" no linux

### ISSUE THREAD

**Issue by ojoaofaria** [renatofmmaia/bomb-bot#23]
Estou configurando no ubuntu 21.04, ao executar o comando para iniciar o bot, recebo o seguinte erro.

![Screenshot from 2022-02-09 20-24-37](https://user-images.githubusercontent.com/1406936/153313666-268d6f15-55e6-40c3-882c-27ff2f47073d.png)

Se eu tentar iniciar com "python3 main.yaml" aparece mais erro ainda.

![image](https://user-images.githubusercontent.com/1406936/153313895-1227e43e-cdc5-4cd6-9b20-b42010cf41c2.png)

Algu[em consegue me ajudar?

**Comment by renatofmmaia** [comment]
Fala @ojoaofaria blza? Na própria doc do bot tem os passos para te ajudar:

- Muitos problemas se rolvem ao atualizar o OS, pois os pacotes da instalação são basicos para o sistema rodar, para atualizar seu linux execute o comando: sudo apt updade && sudo apt upgrade -y
- Se apresentar o erro "No module named 'tkinter'", execute o comando para instalar a interface grafica do python: sudo apt install python3-tk

**Comment by ojoaofaria** [comment]
Obrigado pela resposta @renatofmmaia, nada como falar com quem entende rs.

Me ajuda mais uma vez, por favor.

Apareceu o seguinte erro agora (consegui executar com sua dica anterior).

![image](https://user-images.githubusercontent.com/1406936/153322429-3b0e7780-0538-4eb9-8ed9-5684603acabf.png)

**Comment by renatofmmaia** [comment]
@ojoaofaria nas versões nova do ubuntu, você precisa desativar o wayland, da uma olhada nesse tutorial: https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-20-04-desktop

Vamos atualizar isso na nossa documentação tbm, junto com uma VM que vamos subir com uma distro linux o mais leve possível =)

**Comment by renatofmmaia** [comment]
@ojoaofaria muito obrigado meu amigo, reconhecimento do nosso trabalho é o que nos incentiva :D!
Se tiver um SL tem retorno pra vc certamente rs, grande abraço!
