### ISSUE TITLE
Problema no envio de Print

### ISSUE THREAD

**Issue by Rcfeitosa** [renatofmmaia/bomb-bot#26]
Olá Renato , primeiramente gostaria de parebenisa pelo bot do bomb muito top.

Estou tendo um problema da seguinte forma, usando versão  0.0.3 botbomb todos requisitos instalados, configuado e funcionando. Na parte do telegram quando inicia o bot e vai o 1° print e realizado com sucesso,só que depois nao envia mais , já coloquei varios minutos diferente e nao tive sucesso.

 # Temporizador quando a imagem do seu print é enviada para o telegrama
  refresh_print_chest: 20

Tem idea de que está acontecendo, pode me ajudar ?

**Comment by renatofmmaia** [comment]
Fala @Rcfeitosa agradecemos pelo seu feedback! 
Sobre o temporizador, estranho mesmo, se ao menos um envio é feito com sucesso, não deveria ter dado problema.
Altera a config para 1 min e ativa o log na config "save_log_file = 1".
Executa o bot por 5 min e cola o arquivo de log aqui pf para analisarmos.
