### ISSUE TITLE
Bot não reconhece multiaccount [SOLVED]

### ISSUE THREAD

**Issue by Yumiizera** [renatofmmaia/bomb-bot#32]
Quando executo o comando, ele só reconhece uma aba da pagina.

![image](https://user-images.githubusercontent.com/95440041/153663985-cd3afad9-8cfe-4f75-96cf-dcb006ffc34a.png)

Existe solução porque já troquei até de navegador.

**Comment by andresandri2** [comment]
Abra o terminal e digite:

sudo apt-get install xdotool

Vai resolver seu problema.

**Comment by Yumiizera** [comment]
Eu tinha feito esse comando, mas como to usando VM tive que dar outro comando porque o problema era da minha versão de linux.

**Comment by hiagopinacio** [comment]
Resolveu aí né @Yumiizera ? vou fechar aqui a Issue aqui.
