### ISSUE TITLE
Sugestão de leitura de vida de  baús

### ISSUE THREAD

**Issue by Juninhox13** [renatofmmaia/bomb-bot#34]
Olá, o bot é mto foda mano, ces tao de parabens.
Depois se puderem dar uma olhada nesse daqui, ele le a vida dos baús e coloca os herois pra trabalharem de acordo com a vida dos baús, se vcs conseguissem implementar isso em updates futuros seria o sonho master.
Se nao for pedir muito, tambem incluir os baús de chave. aí nao precisa de mais nada. só lua manos <3
Vlw o espaço para sugestões.  
[Bot Atualizado.zip](https://github.com/renatofmmaia/bomb-bot/files/8054707/Bot.Atualizado.zip)

**Comment by renatofmmaia** [comment]
Fala @Juninhox13 blza? De fato existem varias pensamentos sobre como otimizar o farm, já estamos de olho para construir a nossa logica em cima de raridades de baú tb.
Assim que possível lançaremos novidades =)
