### ISSUE TITLE
Envio do print do baú no telegram.

### ISSUE THREAD

**Issue by Zaiplas** [renatofmmaia/bomb-bot#36]
Primeiramente parabéns pelo trabalho, bot está top, muito rápido.
Tenho 3 contas mas o bot envia o print do baú de apenas duas contas, alguma ideia do que pode ser?

**Comment by renatofmmaia** [comment]
Fala @Zaiplas, blza?!
Vc usa em VM ou VPS?

**Comment by Zaiplas** [comment]
Bahhh não sei o que é VPS. VM é máquina virtual né? Uso no Windows, no chrome.

**Comment by renatofmmaia** [comment]
Você esta deixando as abas maximizadas ou enfileiradas, uma em cima da outra? Lembrando que precisam estar no mesmo monitor.
Se puder compartilhar tb uma imagem de como esta seu monitor com as contas abertas.

**Comment by Zaiplas** [comment]
estou deixando maximizadas uma em cima da outra
![image](https://user-images.githubusercontent.com/59412040/153957684-632dc1c5-9751-45c3-b48a-0ee6183d67e3.png)
![image](https://user-images.githubusercontent.com/59412040/153957719-d8161790-23d4-4369-b46b-885683f2c956.png)
![image](https://user-images.githubusercontent.com/59412040/153957734-8c44341c-0f66-4e04-ad2a-fca7d3b9345f.png)

**Comment by Zaiplas** [comment]
o bot alterna as abas normalmente só o telegram q geralmente envia apenas 2 contas

**Comment by jeffersonsgouveia** [comment]
Boa tarde.
Parabéns pelo trabalho!
Acontece o mesmo comigo. Tenho 4 contas e envia sempre 3 prints.

Peguei o erro no log, segue.
urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by renatofmmaia** [comment]
Obrigado pelas infos pessoal, vamos analisar e procurar uma solução para os erros apontados, como não interferem no funcionamento do farm, adicionei em nosso roadmap, assim que possível vamos liberar essas correções!
Bom farm pra todos ^^
