### ISSUE TITLE
Atualização 23/02 - Não funciona

### ISSUE THREAD

**Issue by Yumiizera** [renatofmmaia/bomb-bot#49]
Após essa nova atualização, ele não clica em mais nada.

OBS: Será implementado a imagem de conectar a metamask que eles adicionaram?

**Comment by Undknoll** [comment]
Aguardando atualizações. Melhor BOT.

**Comment by elviojr** [comment]
Em breve vai ter atualizações. Vamos contribuir.

**Comment by luismello** [comment]
Só refazer a imagem Heroes_Home que funciona.
![2022-02-23](https://user-images.githubusercontent.com/21027864/155322436-1e46a589-19ab-44e9-872a-772565288b6e.png)

**Comment by jeffersonsgouveia** [comment]
Bom dia.
Pra correção, abre o arquivo bombScreen.py (caminho: module/bombscreen.py) com o bloco de notas (notepad ++ como sugestão), vá até linha 182 e após o comando "continue" da linha 185, pule uma linha e cole o trecho:

                logger_translated("login wallet", LoggerEnum.BUTTON_CLICK)
                if not click_when_target_appears("button_connect_login"):
                    refresh_page()
                    continue  
                    
Salve o arquivo.
Apóis isso, tire print da tela nova e salve em: assets/images/targets com o nome do arquivo button_connect_login.png

![button_connect_login](https://user-images.githubusercontent.com/99913258/155323170-bad2ce46-3fdf-4e96-b18e-109db1441fd3.png)

**Comment by krgsilva** [comment]
> Bom Dia. Pra correção, abra o arquivo bombScreen.py (caminho: module/bombscreen.py) com o bloco de notas (notepad ++ como sugestão), vá até a linha 182 e após o comando "continue" da linha 185, pule uma linha e cole o trecho abaixo:
> 
> ```
>             logger_translated("login wallet", LoggerEnum.BUTTON_CLICK)
>             if not click_when_target_appears("button_connect_login"):
>                 refresh_page()
>                 continue  
> ```
> 
> Salve o arquivo. Apóis isso, tire print da tela nova e salve em: assets/images/targets com o nome do arquivo button_connect_login.png
> 
> ![button_connect_login](https://user-images.githubusercontent.com/99913258/155323170-bad2ce46-3fdf-4e96-b18e-109db1441fd3.png)



> > Só refazer a imagem Heroes_Home que funciona.![23-02-2022](https://user-images.githubusercontent.com/21027864/155322436-1e46a589-19ab-44e9-872a-772565288b6e.png)
> 
> Tem nomeada como "butoon_heroes.png", sem aspas.

Fiz o que voces falaram e ta funcionando obrigado !!

**Comment by txcost** [comment]
Para mim

> Bom dia. Pra correção, abra o arquivo bombScreen.py (caminho: module/bombscreen.py) com o bloco de notas (notepad ++ como sugestão), vá até linha 182 e após o comando "continue" da linha 185, pule uma linha e cole o trecho abaixo:
> 
> ```
>             logger_translated("login wallet", LoggerEnum.BUTTON_CLICK)
>             if not click_when_target_appears("button_connect_login"):
>                 refresh_page()
>                 continue  
> ```
> 
> Salve o arquivo. Apóis isso, tire print da tela nova e salve em: assets/images/targets com o nome do arquivo button_connect_login.png
> 
> ![button_connect_login](https://user-images.githubusercontent.com/99913258/155323170-bad2ce46-3fdf-4e96-b18e-109db1441fd3.png)

Para mim o connect novo deu certo, mas o HEROES não funcionou nem como uma imagem minha nem salvando a que mandaram aqui.

**Comment by krgsilva** [comment]
> Para mim
> 
> > Bom dia. Pra correção, abra o arquivo bombScreen.py (caminho: module/bombscreen.py) com o bloco de notas (notepad ++ como sugestão), vá até linha 182 e após o comando "continue" da linha 185, pule uma linha e cole o trecho abaixo:
> > ```
> >             logger_translated("login wallet", LoggerEnum.BUTTON_CLICK)
> >             if not click_when_target_appears("button_connect_login"):
> >                 refresh_page()
> >                 continue  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Salve o arquivo. Apóis isso, tire print da tela nova e salve em: assets/images/targets com o nome do arquivo button_connect_login.png
> > ![button_connect_login](https://user-images.githubusercontent.com/99913258/155323170-bad2ce46-3fdf-4e96-b18e-109db1441fd3.png)
> 
> Para mim o connect novo deu certo, mas o HEROES não funcionou nem como uma imagem minha nem salvando a que mandaram aqui.

Aqui eu tirei print do novo ICONE de heroes e subistituir o antigo e funciono de boa

**Comment by kosicki123** [comment]
> Para mim
> 
> > Bom dia. Pra correção, abra o arquivo bombScreen.py (caminho: module/bombscreen.py) com o bloco de notas (notepad ++ como sugestão), vá até linha 182 e após o comando "continue" da linha 185, pule uma linha e cole o trecho abaixo:
> > ```
> >             logger_translated("login wallet", LoggerEnum.BUTTON_CLICK)
> >             if not click_when_target_appears("button_connect_login"):
> >                 refresh_page()
> >                 continue  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Salve o arquivo. Apóis isso, tire print da tela nova e salve em: assets/images/targets com o nome do arquivo button_connect_login.png
> > ![button_connect_login](https://user-images.githubusercontent.com/99913258/155323170-bad2ce46-3fdf-4e96-b18e-109db1441fd3.png)
> 
> Para mim o connect novo deu certo, mas o HEROES não funcionou nem como uma imagem minha nem salvando a que mandaram aqui.

Mesma coisa aqui

**Comment by seoservicesbr** [comment]
Aqui aparece o erro:

admin@vmi778925:~/bomb$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from module.bombScreen import BombScreen, BombScreenEnum
  File "/home/admin/bomb/module/bombScreen.py", line 188
    if not click_when_target_appears("button_connect_login"):
    ^
IndentationError: unexpected indent

Estou usando linux.

Alguém conseguiu resolver?

**Comment by Yumiizera** [comment]
Salvem a imagem "heroes" como butoon_heroes.png que deve funcionar

**Comment by seoservicesbr** [comment]
> Salvem a imagem "heroes" como butoon_heroes.png que deve funcionar

Já está renomeada corretamente.

**Comment by filiperoger** [comment]
> Sobre o erro admin@vmi778925:~/bomb$ python3 main.py Traceback (most recent call last): File "main.py", line 8, in from module.bombScreen import BombScreen, BombScreenEnum File "/home/admin/bomb/module/bombScreen.py", line 190 continue ^ IndentationError: unexpected indent
> 
> é importante manter exatamente os espaços no inicio do texto no arquivo bombScreen.py ![identacao](https://user-images.githubusercontent.com/99913258/155339618-8fe02c9d-a925-4e68-950a-96604da3a8f4.png) . Para facilitar, basta seguir a identação da linha acima...vou anexar a imagem de como está o meu.

Fiz exatamente isso, ele faz login de boa, mas não clica no HEROES, ja até coloquei imagem propria mas não funciona, alguem me ajuda?

**Comment by Jiffersantos** [comment]
> > Sobre o erro admin@vmi778925:~/bomb$ python3 main.py Traceback (most recent call last): File "main.py", line 8, in from module.bombScreen import BombScreen, BombScreenEnum File "/home/admin/bomb/module/bombScreen.py", line 190 continue ^ IndentationError: unexpected indent
> > é importante manter exatamente os espaços no inicio do texto no arquivo bombScreen.py ![identacao](https://user-images.githubusercontent.com/99913258/155339618-8fe02c9d-a925-4e68-950a-96604da3a8f4.png) . Para facilitar, basta seguir a identação da linha acima...vou anexar a imagem de como está o meu.
> 
> Fiz exatamente isso, ele faz login de boa, mas não clica no HEROES, ja até coloquei imagem propria mas não funciona, alguem me ajuda?

Estou com o mesmo problema

**Comment by mittwz** [comment]
> > Fiz exatamente isso, ele faz login de boa, mas não clica no HEROES, ja até coloquei imagem propria mas não funciona, alguem me ajuda?
> 
> Estou com o mesmo problema

Hahaha, também estou assim pessoal, acho que só nos resta aguardar...
O login até faz, só não clica em heroes e nem no hunt, pelo menos pra mim...

**Comment by seoservicesbr** [comment]
> Sobre o erro admin@vmi778925:~/bomb$ python3 main.py Traceback (most recent call last): File "main.py", line 8, in from module.bombScreen import BombScreen, BombScreenEnum File "/home/admin/bomb/module/bombScreen.py", line 190 continue ^ IndentationError: unexpected indent
> 
> é importante manter exatamente os espaços no inicio do texto no arquivo bombScreen.py ![identacao](https://user-images.githubusercontent.com/99913258/155339618-8fe02c9d-a925-4e68-950a-96604da3a8f4.png) . Para facilitar, basta seguir a identação da linha acima...vou anexar a imagem de como está o meu.

![2022-02-23_12-14-36](https://user-images.githubusercontent.com/76053952/155348463-b76f03ea-7cae-4ba7-8ea1-0f171cf545e4.png)

Aqui está exatamente igual. Tentei editar pelo notepadqq e pelo gedit, achei que poderia ser algum espaço.

**Comment by alantody** [comment]
Galera tenta trocar a imagem "identify_home.png"

**Comment by seoservicesbr** [comment]
@jeffersonsgouveia manda esse arquivo bombScreen.py ai pra gente, talvez resolva.

**Comment by filiperoger** [comment]
[bombScreen.zip](https://github.com/renatofmmaia/bomb-bot/files/8125650/bombScreen.zip)

**Comment by alantody** [comment]
> [bombScreen.zip](https://github.com/renatofmmaia/bomb-bot/files/8125650/bombScreen.zip)
> 
> Pra conectar esta tudo certo, só estou com problemas para colocar pra trabalhar, não clica no botão HEROES, mesmo ja atualizando a imagem

Após fazer o procedimento de adicionar a nova forma de login conforme citado mais encima, trocar essas imagens também:

"identify_home.png"
"button_heroes.png"

**Comment by mittwz** [comment]
> 

Não deu nem pra baixar seus arquivos

**Comment by mittwz** [comment]
> Segue os arquivos que ajustei e está funcional para mim. Uploading screena_images_.zip…

Não deu nem pra baixar seus arquivos

**Comment by seoservicesbr** [comment]
> Segue os arquivos que ajustei e está funcional para mim. Uploading screena_images_.zip…

Não deu pra baixar

**Comment by jeffersonsgouveia** [comment]
Vou tentar enviar 1 por 1

**Comment by filiperoger** [comment]
Conseguir consertar tudo, só baixar e atualizar as informações do telegram.

telegram:
  # Settings for telegram integration 
  token: ""
  chat_id: 


[bomb-bot-master.zip](https://github.com/renatofmmaia/bomb-bot/files/8125935/bomb-bot-master.zip)

**Comment by seoservicesbr** [comment]
> > Conseguir consertar tudo, só baixar e atualizar as informações do telegram.
> 
> Deu o mesmo problema que eu já estava, continua não saindo da tela **HOME**, como se não identificasse as imagens **HEROES** e **HUNT**.
> 
> Sigo aguardando algum feedback sobre o problema.
> 
> ![image](https://user-images.githubusercontent.com/13211496/155362357-a1a63319-4a2e-462f-81f7-8787e63b4329.png)
> 
> Logs:
> 
> ![image](https://user-images.githubusercontent.com/13211496/155363151-7cff5c04-ade7-4a5c-951c-7a2b6665099b.png)

aqui também, mesma coisa.

**Comment by jeffersonsgouveia** [comment]
Poxa, que pena que não está dando pra ajudar.
Aqui pra mim resolveu quando eu mudei a imagem do  "identify_home.png" pegando a borda "xadrez" e também o "button_heroes.png".

**Comment by cristianowelaski** [comment]
> > > Fiz exatamente isso, ele faz login de boa, mas não clica no HEROES, ja até coloquei imagem propria mas não funciona, alguem me ajuda?
> > 
> > 
> > Estou com o mesmo problema
> 
> Hahaha, também estou assim pessoal, acho que só nos resta aguardar... O login até faz, só não clica em heroes e nem no hunt, pelo menos pra mim...
> 
> _Linux Ubuntu_

Aqui está exatamente assim.

**Comment by renatofmmaia** [comment]
O bomb atualizou hoje, já tem uma nova versão do bot disponível para download, só atualizar :D
https://github.com/renatofmmaia/bomb-bot/releases/tag/v0.0.4

**Comment by rafael1777** [comment]
> O bomb atualizou hoje, já tem uma nova versão do bot disponível para download, só atualizar :D https://github.com/renatofmmaia/bomb-bot/releases/tag/v0.0.4

Tem a do multicontas ai amigao? porque essa ta travando em 1 conta só nao muda =(
