### ISSUE TITLE
Não inicia, dá refresh na tela de login

### ISSUE THREAD

**Issue by juniorj1** [renatofmmaia/bomb-bot#54]
←[99m←[99m[02-23 15:58] => 3 Bombcrypto window (s) found←[0m
←[99m←[99m[02-23 15:58] => 💫 Bombcrypto window[1] inicializado em: NOT_FOUND←[0m
←[99m←[99m[02-23 15:58] => 🆘 Check screen error found, restarting....←[0m
←[99m←[99m[02-23 15:58] => 🐧 Performing login action←[0m
←[99m←[99m[02-23 15:58] => 🌍 Refreshing browser!←[0m

Fica dando refresh.

**Comment by renatofmmaia** [comment]
O bomb atualizou hoje, já tem uma nova versão do bot disponível para download, só atualizar :D
https://github.com/renatofmmaia/bomb-bot/releases/tag/v0.0.4

**Comment by juniorj1** [comment]
Foi erro meu. Meu bomb e minha wallet tava em português. Quando voltei pra inglês pegou.
