### ISSUE TITLE
Super Legend Print 

### ISSUE THREAD

**Issue by SkullzOTS** [renatofmmaia/bomb-bot#7]
https://imgur.com/a/nRS8Uue

print do SL

e + uma dica, confesso que ainda não testei o BOT, se oq vou dizer já está correto, apenas ignore!

Eu estava desenvolvendo um BOT com as mesmas funcionalidades, porém estava fazendo as imgs da % de STAMINA de outro modo, para que verificasse por exemplo 50% ou mais, só olhei nos targets aqui que vcs colocaram a img da barra inteira, então possivelmente se eu configurar um herói pra rodar à 50% ele só vai rodar se tiver exatamente 50% se tiver mais q isso, dai ele já não reconheceria! como eu disse, ainda não testei e nem olhei o código! só olhei o arquivo de config e as imgs!

**Comment by SkullzOTS** [comment]
OBS: o print do SL é de um monitor 1920x1080, navegador chrome com zoom em 100%

**Comment by renatofmmaia** [comment]
Fala Skull, primeiramente obrigado pela print, vamos atualizar e se você tiver um SS, da o feedback dps :D.
O bot identifica a imagem mais parecida com o target(imagem), e utilizamos a barra completa para comparação entre as imagens pois teve melhor apuração, ele não identificara a % correta mas tem uma boa precisão.

**Comment by SkullzOTS** [comment]
@renatofmmaia sim, notei isso! já estou utilizando, parabéns o BOT está muito bom!

**Comment by renatofmmaia** [comment]
Obrigado meu amigo, que bom que gostou, vamos soltando updates e novas soluções nft :D
Qql sugestão é sempre bem vinda, abs!
