### ISSUE TITLE
Minha sugestão para melhorar as doações

### ISSUE THREAD

**Issue by claudiomyst** [renatofmmaia/bomb-bot#89]
Olá amigos, fiz uma pequena doação para vocês e não tinha feito antes por achar que muitos já estavam fazendo.

Por esse motivo minha sugestão é que vocês mostrem na tela do bot a quantidade de doação, a cada atualização vocês atualizam os números, ou se tiver como, mostrem dinamicamente esse número de doação.

Acredito que ao ver o número e uma mensagem do tipo (Até o momento 5 pessoas doaram para contribuir com este bot) mais pessoas possam se interessar em doar para manter o trabalho de vocês.

**Comment by wsa7** [comment]
gostei! o bot é o melhor e ainda gratuito!

**Comment by renatofmmaia** [comment]
Obrigado pela sugestão @claudiomyst e pela sua contribuição =)
